[package]
name = "rftools"
version = "0.1.0"
authors = ["Alex Payne <alexander.payne@nottingham.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
needletail = { version = "0.4.1", features = ["compression"] }
fst = "^0.4"
csv = "1.1"
fnv = "1.0.7"
